### ISSUE TITLE
Possible to Eliminate Prefixing Services?

### ISSUE THREAD

**Issue by inviscid** [xsreality/argocd-applicationset-demo#2]
Thanks for the great working prototype.  I have been able to take this example and expand it to handle the "tenant per namespace" approach.  However, I cannot find a way to prevent prefixing the Wordpress app with the tenant ID.  Since each tenant has namespace isolation I would like to have the same service names in each namespace.

Is there a way to stop/prevent the prefixing of services so I end up with just `wordpress` and `mariadb` instead of `hooli-wordpress` and `hooli-mariadb`?

**Comment by xsreality** [comment]
Hi @inviscid, glad to hear this example is helping you :)

The resource names (service and others) come from the the [Wordpress charts](https://github.com/helm/charts/blob/master/stable/wordpress/templates/svc.yaml#L4) itself. By default, the service name will be `.Release.Name` which in case of ArgoCD deployments will be the name of the ArgoCD application. 

You can [override](https://github.com/helm/charts/blob/master/stable/wordpress/templates/_helpers.tpl#L13) this by setting `.Values.fullnameOverride` to your desired value.

**Comment by inviscid** [comment]
Many thanks.  That worked great!

I was worried the ApplicationSet was controlling the service naming in an opinionated way.  This really is quite flexible.
