### ISSUE TITLE
Failed to unmarshal error for git files generator

### ISSUE THREAD

**Issue by lostinopensrc** [xsreality/argocd-applicationset-demo#4]
Hi Abhinav ,

Could you please have a look on this repo : https://github.com/lostinopensrc/homelab-argocd-applicationset , i tried forking your repo and made some changes to try make it deploy grafana helm chart placed under (tenant/grafana) but it seems to be giving me below error . Iam using argocd version 2.5.3. Thanks 

time="2023-02-05T15:40:33Z" level=info msg="Refreshing app status (spec.source differs), level (3)" application=argo-cd/homelab-tenant-appsets

time="2023-02-05T15:40:33Z" level=info msg="Comparing app state (cluster: https://kubernetes.default.svc, namespace: argo-cd)" application=argo-cd/homelab-tenant-appsets

**time="2023-02-05T15:40:35Z" level=info msg="Normalized app spec: {\"status\":{\"conditions\":[{\"lastTransitionTime\":\"2023-02-05T15:40:33Z\",\"message\":\"rpc error: code = FailedPrecondition desc = Failed to unmarshal \\\"tenants-applicationsets.yaml\\\": \\u003cnil\\u003e\",\"type\":\"ComparisonError\"}]}}" application=argo-cd/homelab-tenant-appsets**

time="2023-02-05T15:40:35Z" level=info msg="Updated sync status:  -> Unknown" application=homelab-tenant-appsets dest-namespace=argo-cd dest-server="https://kubernetes.default.svc" reason=ResourceUpdated type=Normal

**Comment by xsreality** [comment]
Hi @lostinopensrc, I saw you posted the issue in ArgoCD Slack and got a solution. Is it working now?

**Comment by lostinopensrc** [comment]
Yes @xsreality  its working now. Will close this issue.
